steps:
      - id: Set default Environment Variables and prepare Environment
        name: "bash"
        args:
        - -c
        - |
          export BYPASS_REPOSCAN=0 &&
          export BYPASS_OSS_LICENSE=0 &&
          export BYPASS_IMAGESCAN=0 &&
          export BYPASS_WF=0 &&
          export BYPASS_SANDBOX=1 &&
          export K8S_CLUSTER="central" &&
          export CLUSTER_ZONE="us-central1-b" &&
          env > build_vars &&
          chmod +x /workspace/files/*

      - id: Download Utilities
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          curl -s -k -u $$TL_USER:$$TL_PASS "$$TL_CONSOLE/api/v1/util/twistcli" -v -o twistcli;chmod +x twistcli
          curl https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o jq;chmod +x jq
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

      - id: Repo Vulnerability scan
        name: "ubuntu"
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          apt-get update -y;apt-get install -y jq curl &&
          /workspace/files/test.sh $$BYPASS_REPOSCAN
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

availableSecrets:
  secretManager:
  - versionName: projects/pcc-dev-sandbox/secrets/TL_USER/versions/latest
    env: TL_USER
  - versionName: projects/pcc-dev-sandbox/secrets/TL_PASS/versions/latest
    env: TL_PASS
  - versionName: projects/pcc-dev-sandbox/secrets/TL_CONSOLE/versions/latest
    env: TL_CONSOLE
