steps:
      - id: Set default Environment Variables and prepare Environment
        name: "bash"
        args:
        - -c
        - |
          export BYPASS_REPOSCAN=0 &&
          export BYPASS_OSS_LICENSE=0 &&
          export BYPASS_IMAGESCAN=0 &&
          export BYPASS_WF=0 &&
          export BYPASS_SANDBOX=1 &&
          export K8S_CLUSTER="central" &&
          export CLUSTER_ZONE="us-central1-b" &&
          env > build_vars &&
          chmod +x /workspace/files/*

      - id: Download twistcli
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          curl -s -k -u $$TL_USER:$$TL_PASS "$$TL_CONSOLE/api/v1/util/twistcli" -v -o twistcli;chmod +x twistcli
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

      - id: Run Bridgecrew/Checkov IaC scanning
        name: 'bridgecrew/checkov:latest'
        entrypoint: /bin/bash
        args:
        - -c
        - |
          source build_vars &&
          checkov --bc-api-key $$BRIDGECREW_API_KEY --directory $$LOCAL_REPO_DIR --soft-fail
        secretEnv: ['BRIDGECREW_API_KEY']

      - id: Repo Vulnerability scan
        name: "ubuntu"
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          apt-get update -y;apt-get install -y jq curl &&
          /workspace/files/test.sh $$BYPASS_REPOSCAN
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

      - id: OSS License Check 
        name: 'ubuntu'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          apt-get update -y;apt-get install -y jq curl &&
          /workspace/files/licenseCheck.sh $$BYPASS_OSS_LICENSE
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

      - id: Apply security policies (Policy-as-Code) for evilpetclinic Application
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          /workspace/files/addPolicies.sh
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

      - id: Scan Image for vulnerabilities
        name: 'ubuntu'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          apt-get update -y;apt-get install -y jq curl &&
          /workspace/files/scanImage.sh $$BYPASS_IMAGESCAN
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']
     
      - id: Scan Image for Malware using Wildfire
        name: 'ubuntu'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          apt-get update -y;apt-get install -y jq curl &&
          /workspace/files/malwareCheck.sh $$BYPASS_WF
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

      - id: Sandbox Runtime Scanning of Image       
        name: 'ubuntu'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          apt-get update -y;apt-get install -y jq curl &&
          /workspace/files/sandboxscan.sh $$BYPASS_SANDBOX
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']
       
      - id: Deploy Application   
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          gcloud container clusters get-credentials $$K8S_CLUSTER --zone $$CLUSTER_ZONE --project $$PROJECT_ID &&
          /workspace/files/deploy.sh
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']
       
      - id: Execute Runtime attacks 
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          gcloud container clusters get-credentials $$K8S_CLUSTER --zone $$CLUSTER_ZONE --project $$PROJECT_ID &&
          /workspace/files/runtime_attacks.sh
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']
         
      - id: Execute WAAS attacks 
        name: 'gcr.io/cloud-builders/gcloud'
        entrypoint: "bash"
        args:
        - -c
        - |
          source build_vars &&
          gcloud container clusters get-credentials $$K8S_CLUSTER --zone $$CLUSTER_ZONE --project $$PROJECT_ID &&
          /workspace/files/waas_attacks.sh
        secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']

availableSecrets:
  secretManager:
  - versionName: projects/pcc-dev-sandbox/secrets/TL_USER/versions/latest
    env: TL_USER
  - versionName: projects/pcc-dev-sandbox/secrets/TL_PASS/versions/latest
    env: TL_PASS
  - versionName: projects/pcc-dev-sandbox/secrets/TL_CONSOLE/versions/latest
    env: TL_CONSOLE
