---
apiVersion: v1
kind: Namespace
metadata:
  name: evil
  labels:
    name: evil

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evilpetclinic
  namespace: evil
  labels:
    app: evilpetclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evilpetclinic
  strategy: {}
  template:
    metadata:
      labels:
        app: evilpetclinic
    spec:
      containers:
      - image: itresoldi/evilpetclinic:latest
        name: evilpetclinic
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          name: evilpetclinic
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      securityContext:
        runAsUser: 0
      hostNetwork: false
